version: '3'
services:
  db:
    image: solviofoundation/amos_db:latest
    ports:
      - 7473:7473
      - 7474:7474
      - 7687:7687

  api:
    image: solviofoundation/amos_api:latest
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - GRAPHQL_PORT=80
      - NEO4J_URI=bolt://localhost:7687