version: '3.7'
services:
  db:
    build: ./db
    container_name: amos_db
    ports:
      - 7473:7473
      - 7474:7474
      - 7687:7687

  api:
    build: ./api
    container_name: amos_api
    ports:
      - 4000:4000
      - 4001:4001
    environment:
      - NEO4J_URI=bolt://db:7687 
    links:
    - db
    depends_on:
    - db
    volumes:
      - ./api:/app # 
      - /app/node_modules # data volume

  web:
    build: ./web
    container_name: amos_web
    # command: 
    ports:
      - 80:3000
      - 8080:8080
    links:
    - api
    depends_on:
    - api
    # environment:
      # - CUSTOM_API_URL=http://api:4001
    volumes:
      - ./web:/app
      - /app/node_modules # data volume

volumes:
  api-nm:
    external: true