type Topic {
  # id: ID!
  _id: ID!
  names: [String!]!
  # children: [IS_PART_OF!]!
  # parents: [IS_PART_OF!]!
  # amosGames: [FOR_TOPIC!]!
  # getChildrenRec (level: Int!): [Path!]!
  getChildrenRec (level: Int!): [String!]!
  getMostCommonPrerequisites: [String!]!
  getTopResources: [Resource!]! @cypher (statement:
    """
    match (this)
    <-[:FOR_TOPIC]->(a:AmosGame)-[:FOR_RESOURCE]->(r:Resource)
    with r return r
    """
  )
  createLink (name: String!): String!
}

type IS_PART_OF @relation (name: "IS_PART_OF") {
  from: Topic!
  to: Topic!
}

input CreateTopicInput {
  names: [String!]!
}

input AddIsPartOfInput {
  parent: ID!
  child: ID!
}

# type Path {
#   list: [String!]!
# }

type AutocompleteResult {
  name: String!
  topic: Topic!
}

extend type Query {
  # TODO: Change to [Path!]!
  # topic (name: String!): Topic!
  autocomplete (str: String!, first: Int): [AutocompleteResult!]!
}

extend type Mutation {
  # createTopic (input: CreateTopicInput!): Topic! @hasRole (roles: [ADMIN])
  createTopic (input: CreateTopicInput!): Boolean!
  addIsPartOf (input: AddIsPartOfInput!): Boolean!
  # addIsPartOf (name: String!, names: [String!]!, _id: String): Topic!
}